
export const ADD_USER = "ADD_USER"
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS"
export const ADD_USER_FAILURE = "ADD_USER_FAILURE"


export const USER_LOGIN = "USER_LOGIN"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE"

export const USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"



export const ADD_POST = "ADD_POST"
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS"
export const ADD_POST_FAILURE = "ADD_POST_FAILURE"



export const GET_ALLPOST_LIST="GET_ALLPOST_LIST"
export const GET_ALLPOST_SUCCESS="GET_ALLPOST_SUCCESS"
export const GET_ALLPOST_FAILURE="GET_ALLPOST_FAILURE"
export const SIGN_OUT="SIGN_OUT"
export const USER_LOGOUT_SUCCESS="USER_LOGOUT_SUCCESS"

export const GET_POST_AUTHOR_NAME="GET_POST_AUTHOR_NAME"
export const DELETE_POST="DELETE_POST"

export const DELETE_USERPOST_SUCCESS="DELETE_USERPOST_SUCCESS"
export const DELETE_USERPOST_fAILURE="DELETE_USERPOST_fAILURE"


export const ADD_COMMENTS="ADD_COMMENTS"
export const ADD_COMMENT_SUCCESS="ADD_COMMENT_SUCCESS"
export const ADD_COMMENT_FAILURE="ADD_COMMENT_FAILURE"

export const GET_ALLCOMMENT_LIST="GET_ALLCOMMENT_LIST"
export const GET_ALLCOMMENTS_SUCCESS="GET_ALLCOMMENTS_SUCCESS"
export const GET_ALLCOMMENTS_FAILURE="GET_ALLCOMMENTS_FAILURE"

export const GET_COMMENT_AUTHOR_NAME="GET_COMMENT_AUTHOR_NAME"

export const SEARCH_POST="SEARCH_POST"
export const SEARCH_POST_SUCCESS="SEARCH_POST_SUCCESS"
export const SEARCH_POST_fAILURE="SEARCH_POST_fAILURE"

export const ADD_LIKES="ADD_LIKES"
export const ADD_LIKES_SUCCESS="ADD_LIKES_SUCCESS"
export const ADD_LIKES_FAILURE="ADD_LIKES_FAILURE"

export const GET_ALL_LIKES="GET_ALL_LIKES"
export const GET_ALLLIKES_SUCCESS="GET_ALLLIKES_SUCCESS"
export const GET_ALLLIKES_FAILURE="GET_ALLLIKES_FAILURE"



